// const res = Array(8208 - 8207 + 0)
// .fill().map((_, idx) => 8207 + idx)

// console.log(res, 18.0 * 14.2 * 1.5);

const path = require("path");
const _ = require("lodash");

const imageExtensions = ["", "jpeg", "jpg", "png", "bmp", "gif", "tiff", "tif"];

const extensions = new Set(imageExtensions);

const bokbasen = {
  ProductSupply: {
    SupplyDetail: {
      Price: {
        Tax: { TaxType: 1, TaxRateCode: "Z", TaxRatePercent: 0 },
        PriceType: 2,
        PriceAmount: 449,
        CurrencyCode: "NOK",
        PriceQualifier: 5,
      },
      Supplier: {
        SupplierName: "FS",
        SupplierRole: 6,
        SupplierIdentifier: { IDValue: 7080005055932, SupplierIDType: 6 },
      },
      ProductAvailability: 21,
    },
    MarketPublishingDetail: {
      MarketPublishingStatus: 4,
      MarketPublishingStatusNote: "Grønn",
    },
  },
  RecordReference: "no.bokbasen.150178495",
  RelatedMaterial: {
    RelatedProduct: {
      ProductIdentifier: {
        IDValue: 20160126101020936,
        IDTypeName: "Bokbasen_AlternativeFormat",
        ProductIDType: 1,
      },
      ProductRelationCode: 6,
    },
  },
  CollateralDetail: {
    TextContent: [
      {
        Text: "Jamies har blitt helsebevisst! Med hans herlige mat forebygger du nå sykdom, blir noen kilo lettere og litt gladere. \n \nEtter snart 30 år på kjøkkenet (og tett opp til egen 40-årsdag) bestemte Jamie seg for å lage en kokebok hvor all maten var med på å sikre helsen til den som bruker boken. Derfor har det blitt den boken som Jamie har lagt mest arbeid i og den har allerede endret livet hans. Målet er at den også skal være et viktig steg i riktig retning for alle som bruker boken. Jamie har brukt nesten to år på å intervjue og møte ernæringseksperter, forskere og professorer. Sammen med teamet sitt har han utarbeidet et nittitalls oppskrifter som kiler smaksløkene dine og gir deg balanserte måltider som inneholder næringsstoffer som gjør deg friskere og gir deg energi og humør til å takle alt du har lyst til å gjøre. De fleste som bruker denne boken vil merke at vekten går ned og humøret går opp. \nVed å bruke en håndfull av rådene i denne boken, har du redskap til å få et sunnere liv! \nFor første gang har Jamie tatt alle bildene til boken selv. Imponerende. \nJamie Oliver er en verdenskjent kokk, forfatter og tv-personlighet, dette er hans 13. bok på norsk.",
        TextType: 3,
        ContentAudience: 0,
      },
      {
        Text: "Undertittel på løst omslag: hverdagsmat du blir friskere og gladere av",
        TextType: 1,
        ContentAudience: 0,
        TextSourceCorporate: "Bokbasen_Note",
      },
    ],
    SupportingResource: [
      {
        ResourceMode: 3,
        ContentAudience: 2,
        ResourceVersion: {
          ResourceForm: 2,
          ResourceLink:
            "https://api.boknett.no/metadata/export/object/download?id=OjNLhePKuI3veKdKEp%2BlQ86Nhm6Bc2hB090EdZMIdoPvpLSAMgtQKn35QU4aWl%2Fd",
          ResourceVersionFeature: {
            FeatureNote: "ol.jpg",
            ResourceVersionFeatureType: 4,
          },
        },
        ResourceContentType: 1,
      },
      {
        ResourceMode: 3,
        ContentAudience: 2,
        ResourceVersion: {
          ResourceForm: 2,
          ResourceLink:
            "https://api.boknett.no/metadata/export/object/download?id=hE6mwX%2FAEetrwNJKLeg3%2Fs6Nhm6Bc2hB090EdZMIdoPvpLSAMgtQKn35QU4aWl%2Fd",
          ResourceVersionFeature: {
            FeatureNote: "os.jpg",
            ResourceVersionFeatureType: 4,
          },
        },
        ResourceContentType: 1,
      },
      {
        ResourceMode: 3,
        ContentAudience: 2,
        ResourceVersion: {
          ResourceForm: 2,
          ResourceLink:
            "https://api.boknett.no/metadata/export/object/download?id=n3Zf1pyBmOXp7sSpdFSLjfsIf%2BMGQ1s%2FPqRH43oYl5%2BnuIltz5hINTm0SBYqaqfk",
          ResourceVersionFeature: {
            FeatureNote: "org.jpg",
            ResourceVersionFeatureType: 4,
          },
        },
        ResourceContentType: 1,
      },
      {
        ResourceMode: 6,
        ContentAudience: 0,
        ResourceVersion: {
          ResourceForm: 3,
          ResourceLink:
            "http://issuu.com/gyldendalnorskforlag/docs/jamies_supermat/1?e=1324688/33391271",
        },
        ResourceContentType: 16,
      },
    ],
  },
  NotificationType: 3,
  PublishingDetail: {
    Imprint: {
      ImprintName: "Gyldendal",
      ImprintIdentifier: {
        IDValue: 663852,
        IDTypeName: "Bokbasen_ImprintID",
        ImprintIDType: 1,
      },
    },
    Publisher: {
      PublisherName: "Gyldendal Norsk Forlag AS",
      PublishingRole: 1,
      PublisherIdentifier: [
        { IDValue: 2, IDTypeName: "Bokbasen_Kundenummer", PublisherIDType: 1 },
        { IDValue: 7080005055932, PublisherIDType: 6 },
      ],
    },
    PublishingDate: [
      { Date: 2016, PublishingDateRole: 1 },
      { Date: 2016, PublishingDateRole: 12 },
      { Date: 20160120, PublishingDateRole: 11 },
    ],
    LatestReprintNumber: 1,
  },
  RecordSourceType: 4,
  DescriptiveDetail: {
    Extent: { ExtentType: 0, ExtentUnit: 3, ExtentValue: 309 },
    Measure: [
      { MeasureType: 8, Measurement: 1210, MeasureUnitCode: "gr" },
      { MeasureType: 1, Measurement: 255, MeasureUnitCode: "mm" },
      { MeasureType: 2, Measurement: 200, MeasureUnitCode: "mm" },
      { MeasureType: 3, Measurement: 37, MeasureUnitCode: "mm" },
    ],
    Subject: [
      { SubjectCode: 326, SubjectSchemeIdentifier: 37 },
      { SubjectCode: 31010, SubjectSchemeIdentifier: 38 },
      {
        SubjectCode: "WBH",
        SubjectHeadingText: "Diett og helsekost",
        SubjectSchemeIdentifier: 93,
      },
      {
        SubjectCode: "WBB",
        SubjectHeadingText: "Kokebøker av kjente personer",
        SubjectSchemeIdentifier: 93,
      },
      {
        SubjectSchemeName: "Bokbasen_Subject",
        SubjectHeadingText: "Ernæring",
        SubjectSchemeIdentifier: 24,
      },
      {
        SubjectSchemeName: "Bokbasen_Subject",
        SubjectHeadingText: "Helsekost",
        SubjectSchemeIdentifier: 24,
      },
      {
        SubjectSchemeName: "Bokbasen_Form",
        SubjectHeadingText: "Kokebøker",
        SubjectSchemeIdentifier: 24,
      },
      {
        SubjectSchemeName: "Bokbasen_LitteraryType",
        SubjectHeadingText: "Faglitteratur",
        SubjectSchemeIdentifier: 24,
      },
      { SubjectHeadingText: "641.5/637", SubjectSchemeIdentifier: 46 },
    ],
    Audience: {
      AudienceCodeType: 2,
      AudienceCodeValue: "Voksen",
      AudienceCodeTypeName: "Bokbasen_Audience",
    },
    Language: [
      { LanguageCode: "nob", LanguageRole: 1 },
      { LanguageCode: "eng", LanguageRole: 2 },
    ],
    Contributor: [
      {
        NameType: 4,
        NameIdentifier: [
          {
            IDValue: 669937,
            IDTypeName: "Bokbasen_ProprietaryID",
            NameIDType: 1,
          },
          { IDValue: 1033496, NameIDType: 36 },
          { IDValue: 120185514, NameIDType: 16 },
        ],
        SequenceNumber: 1,
        ContributorDate: { Date: 1975, ContributorDateRole: 50 },
        ContributorRole: "A01",
        ContributorPlace: { CountryCode: "GB", ContributorPlaceRelator: 1 },
        PersonNameInverted: "Oliver, Jamie",
      },
      {
        NameType: 4,
        NameIdentifier: [
          {
            IDValue: 690937,
            IDTypeName: "Bokbasen_ProprietaryID",
            NameIDType: 1,
          },
          { IDValue: 10025447, NameIDType: 36 },
          { IDValue: 365594017, NameIDType: 16 },
        ],
        SequenceNumber: 2,
        ContributorDate: { Date: 1965, ContributorDateRole: 50 },
        ContributorRole: "B06",
        ContributorPlace: { CountryCode: "NO", ContributorPlaceRelator: 1 },
        PersonNameInverted: "Kristoffersen, Lisbeth",
      },
      {
        NameType: 4,
        NameIdentifier: [
          {
            IDValue: 669937,
            IDTypeName: "Bokbasen_ProprietaryID",
            NameIDType: 1,
          },
          { IDValue: 1033496, NameIDType: 36 },
          { IDValue: 120185514, NameIDType: 16 },
        ],
        SequenceNumber: 3,
        ContributorDate: { Date: 1975, ContributorDateRole: 50 },
        ContributorRole: "A12",
        ContributorPlace: { CountryCode: "GB", ContributorPlaceRelator: 1 },
        PersonNameInverted: "Oliver, Jamie",
      },
      {
        NameType: 4,
        NameIdentifier: [
          {
            IDValue: 719604,
            IDTypeName: "Bokbasen_ProprietaryID",
            NameIDType: 1,
          },
          { IDValue: 1453362517438, NameIDType: 36 },
        ],
        SequenceNumber: 4,
        ContributorRole: "A12",
        PersonNameInverted: "Stuart, Paul",
      },
      {
        NameType: 4,
        NameIdentifier: [
          {
            IDValue: 719605,
            IDTypeName: "Bokbasen_ProprietaryID",
            NameIDType: 1,
          },
          { IDValue: 1453362517440, NameIDType: 36 },
        ],
        SequenceNumber: 5,
        ContributorRole: "A12",
        ContributorPlace: { CountryCode: "GB", ContributorPlaceRelator: 1 },
        PersonNameInverted: "Claire, Freddie",
      },
    ],
    Illustrated: 2,
    ProductForm: "BB",
    TitleDetail: [
      {
        TitleType: 1,
        TitleElement: {
          TitleText: "Jamies supermat",
          SequenceNumber: 1,
          TitleElementLevel: 1,
        },
      },
      {
        TitleType: 3,
        TitleElement: {
          TitleText: "Everyday super food",
          TitleElementLevel: 1,
        },
      },
    ],
    EditionNumber: 1,
    ProductComposition: 0,
    ProductClassification: {
      ProductClassificationCode: "Bok",
      ProductClassificationType: 7,
    },
  },
  ProductIdentifier: [
    { IDValue: 9788205491021, ProductIDType: 3 },
    { IDValue: 9788205491021, ProductIDType: 15 },
    {
      IDValue: 150178495,
      IDTypeName: "Bokbasen_ProprietaryID",
      ProductIDType: 1,
    },
  ],
  RecordSourceIdentifier: {
    IDValue: 2,
    IDTypeName: "Bokbasen",
    RecordSourceIDType: 1,
  },
};

// const getImageCover = (el, position = 0) => {
//     const links = _.map(_.get(el,'CollateralDetail.SupportingResource'), (url) => { if(!url.ResourceVersion.ResourceLink.includes('3d')) return url } )
//     return _.get(links[position], 'ResourceVersion.ResourceLink')
// }

// const bk = {
//     smallImage: getImageCover(bokbasen, 0),
//     fullImage: getImageCover(bokbasen, 1),
// }

// console.log('book with images ', bk);

const imageUrl = "http://bibl.sh.se/media/images/medium/diva2_525011.jpg";

const fileExt = path.extname(imageUrl).slice(1).toLowerCase();

const extractedExt =
  fileExt && fileExt.includes("?") ? fileExt.split("?")[0] : fileExt;

console.log(extractedExt, imageExtensions.includes(extractedExt));

const c1 = !imageExtensions.includes(extractedExt);
const c2 = !extensions.has(path.extname(imageUrl).slice(1).toLowerCase());

console.log(c1, c2, extensions);

if (!imageUrl || imageUrl === "" || !extensions.has(extractedExt)) {
  console.log("Will return null ");
} else {
  console.log("good file path");
}

console.log(
  JSON.stringify({
    s3Key: "output/onix/upd/arttot.xml_onix.xml",
  })
);

const AllCountcount = 450;
const fileSize = 90;

const steps = Math.ceil(AllCountcount / fileSize);

const skip = [];

for (let i = 0; i < steps; i++) {
  skip.push(i * fileSize);
}

console.log("the sets is ", steps, " per processing. skip ", skip);

const bookSale = {
  Sales: [
    {
      price: 123,
      id: 57104,
      status: "available",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "meetup",
      currency: "SEK",
      guid: "fb438e50-1022-4898-bd2e-99ead9695969",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-16T07:57:45.949Z",
      updatedAt: "2021-10-22T07:30:33.771Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57120,
      status: "available",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "meetup",
      currency: "SEK",
      guid: "529ad490-2f88-407c-8dec-209b924f7bdd",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-21T07:19:06.078Z",
      updatedAt: "2021-10-08T10:30:59.142Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57116,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "c198bd33-bc2d-46d1-9b0e-342802164b99",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-21T07:04:33.863Z",
      updatedAt: "2021-09-21T10:19:26.497Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57117,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "db5d875c-80d8-44fe-8a8b-de189add1ece",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-21T07:04:45.006Z",
      updatedAt: "2021-09-21T07:07:00.344Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57115,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "21ae8a3f-c60c-4052-ab20-f23770087232",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-20T14:35:24.365Z",
      updatedAt: "2021-09-20T14:56:15.515Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57114,
      status: "available",
      format: "paperback",
      condition: "acceptable",
      comment: "NewBook",
      delivery: "meetup",
      currency: "SEK",
      guid: "4448f011-8d4d-4645-8945-b9dddddd2602",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-20T14:35:13.929Z",
      updatedAt: "2021-10-08T10:30:59.142Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57113,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "NewBook",
      delivery: "both",
      currency: "SEK",
      guid: "8aeb195b-68f6-4590-9c87-1d7229a2832e",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-20T14:21:01.130Z",
      updatedAt: "2021-09-20T14:33:01.209Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123450,
      id: 57106,
      status: "deleted",
      format: "paperback",
      condition: "acceptable",
      comment: "CommentNyBook",
      delivery: "both",
      currency: "SEK",
      guid: "3d8b6543-f6e7-4972-b1ff-dea77452ad17",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-16T08:13:16.143Z",
      updatedAt: "2021-09-20T08:22:29.895Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57107,
      status: "deleted",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "1710c620-9330-4267-9f04-0a7579351bc4",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-16T09:15:12.906Z",
      updatedAt: "2021-09-20T08:10:11.157Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 450,
      id: 57049,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "CommentNyBook",
      delivery: "both",
      currency: "SEK",
      guid: "23ce468f-e1a7-4a82-bc08-7a5437990ea6",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-14T09:28:50.250Z",
      updatedAt: "2021-09-20T07:58:29.805Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57102,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "NewBook",
      delivery: "both",
      currency: "SEK",
      guid: "fb599e6b-cd08-4949-bade-ab86d5836308",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-15T13:07:45.857Z",
      updatedAt: "2021-09-20T07:51:04.380Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57108,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "8c91fc34-ffbc-478d-a1cb-4063d143f5f1",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-16T09:15:23.726Z",
      updatedAt: "2021-09-16T11:00:26.331Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57105,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "546272c6-1975-45be-bbb9-c2a6f3f936d9",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-16T08:13:05.798Z",
      updatedAt: "2021-09-16T08:55:16.175Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57103,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "14a02331-9167-4598-bc8f-0aea6ecaca95",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-15T13:07:56.797Z",
      updatedAt: "2021-09-15T13:10:20.881Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57047,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "8df353c1-1b52-474b-a0ef-57f13359ad54",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-14T09:28:26.815Z",
      updatedAt: "2021-09-15T13:05:08.622Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57042,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "de10fdcc-86ad-4365-8eb1-34ad0a49c9e4",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-14T07:46:16.568Z",
      updatedAt: "2021-09-15T12:40:58.799Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57101,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "04a9426c-f175-469e-96df-d05baceb2fa7",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-15T11:57:14.067Z",
      updatedAt: "2021-09-15T12:36:47.201Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 450,
      id: 57040,
      status: "deleted",
      format: "paperback",
      condition: "acceptable",
      comment: "CommentNyBook",
      delivery: "both",
      currency: "SEK",
      guid: "89a6688e-0e72-42ca-b148-9362a27642de",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-14T07:45:53.130Z",
      updatedAt: "2021-09-15T10:13:21.430Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 222,
      id: 57041,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "bbe0d765-05f3-4842-affa-e0b537ce81cd",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-14T07:46:05.209Z",
      updatedAt: "2021-09-15T07:56:05.094Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 123,
      id: 57048,
      status: "requested",
      format: "paperback",
      condition: "acceptable",
      comment: "",
      delivery: "both",
      currency: "SEK",
      guid: "3b64a983-6548-44fa-abf9-71ad0da88016",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-09-14T09:28:39.119Z",
      updatedAt: "2021-09-15T07:50:29.912Z",
      BookId: 48732,
      SellerId: 49459,
    },
    {
      price: 219,
      id: 12273,
      status: "deleted",
      format: "paperback",
      condition: "good",
      comment:
        "Bra skick använd en termin, har några understrykningar i viktiga kapitel i bokens index. Men den klarar absolut några terminer till. ",
      delivery: "both",
      currency: "SEK",
      guid: "51ea9e3d-18f6-4d35-9ef6-54f2f01e5961",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-02-01T13:35:04.076Z",
      updatedAt: "2021-02-01T13:35:04.076Z",
      BookId: 48732,
      SellerId: 19468,
    },
    {
      price: 450,
      id: 3048,
      status: "deleted",
      format: "paperback",
      condition: "like new",
      comment: null,
      delivery: "shipping",
      currency: "SEK",
      guid: "27bfefd7-c091-40fc-87f6-d612d66662e1",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2020-09-12T14:59:22.888Z",
      updatedAt: "2020-09-12T15:02:06.537Z",
      BookId: 48732,
      SellerId: 1527,
    },
    {
      price: 400,
      id: 1967,
      status: "deleted",
      format: "paperback",
      condition: "like new",
      comment:
        "Fint skick, senaste upplagan utan understrykningar. Har även övningsbok till av senaste upplagan. ",
      delivery: "shipping",
      currency: "SEK",
      guid: "7b5ee05e-c97a-4089-b55b-65c47c2df276",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2020-08-31T14:57:39.798Z",
      updatedAt: "2020-08-31T14:57:39.798Z",
      BookId: 48732,
      SellerId: 1077,
    },
    {
      price: 250,
      id: 9048,
      status: "deleted",
      format: "paperback",
      condition: "like new",
      comment: "Boken finns i Stockholm",
      delivery: "meetup",
      currency: "SEK",
      guid: "0d1811c4-6dea-461a-a6b1-cb78846e4be3",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-01-13T08:50:31.771Z",
      updatedAt: "2021-02-21T09:51:45.473Z",
      BookId: 48732,
      SellerId: 9086,
    },
    {
      price: 150,
      id: 10255,
      status: "deleted",
      format: "paperback",
      condition: "very good",
      comment: "",
      delivery: "meetup",
      currency: "SEK",
      guid: "6df5c6f8-a902-4e51-abbc-d0b76c3b7160",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-01-18T19:23:33.167Z",
      updatedAt: "2021-01-18T19:53:36.604Z",
      BookId: 48732,
      SellerId: 16534,
    },
    {
      price: 195,
      id: 13848,
      status: "sold",
      format: "paperback",
      condition: "like new",
      comment: "",
      delivery: "shipping",
      currency: "SEK",
      guid: "ecc08762-d2a1-4012-b00b-b44a2ab4a6b2",
      returnDate: null,
      onHand: null,
      mainSaleId: null,
      createdAt: "2021-02-14T22:59:20.729Z",
      updatedAt: "2021-09-27T17:06:16.808Z",
      BookId: 48732,
      SellerId: 24961,
    },
  ],
  orders: [
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20688,
      guid: "9908b34a-ae74-4ffe-8a15-602a12097122",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "delivered",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+4700000000",
      buyerEmail: "testonetest81412@gmail.com",
      buyerFirstName: "Andri",
      buyerLastName: "Manri",
      buyerFullName: "Andri Manri",
      buyerBirthday: null,
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "1",
      buyerEntrance: "X",
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16435",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "1",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: "X",
      saZip: "16435",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-14T11:06:32.283Z",
      updatedAt: "2021-09-14T11:06:36.004Z",
      BuyerId: 49457,
      MerchantId: 34,
      ShippingAddressId: 36808,
      TransactionId: 23824,
      ShippingOrderId: 21579,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20690,
      guid: "59fb1518-c8af-4a5a-9f85-141648765b93",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-15T11:41:11.319Z",
      updatedAt: "2021-09-15T11:41:15.316Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23837,
      ShippingOrderId: 21583,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20692,
      guid: "9a7fe1a2-842e-4cf5-95eb-4d3a2b253283",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-17T08:04:52.641Z",
      updatedAt: "2021-09-17T08:04:56.866Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23877,
      ShippingOrderId: 21585,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20693,
      guid: "18198781-2e97-4c0c-895c-9cf478f80300",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-20T08:03:57.841Z",
      updatedAt: "2021-09-20T08:04:01.485Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23884,
      ShippingOrderId: 21588,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20697,
      guid: "b900e245-c764-4649-a8df-824ccf357665",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-21T07:08:00.092Z",
      updatedAt: "2021-09-21T07:08:03.596Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23894,
      ShippingOrderId: 21594,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20700,
      guid: "129c843e-916a-4489-968e-0bb6fdee2bd2",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-10-08T09:41:44.522Z",
      updatedAt: "2021-10-08T09:41:48.500Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23901,
      ShippingOrderId: 21598,
      ShippingMethodId: 1,
    },
    {
      price: 578,
      vat: 35,
      discount: 0,
      certDiscount: null,
      shippingTax: 0,
      total: 578,
      shippingPrice: 0,
      saFloorNo: null,
      saFlatNo: null,
      id: 20707,
      guid: "c86d8134-5cf3-4528-b62b-14141c0794e9",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-10-25T07:01:12.526Z",
      updatedAt: "2021-10-25T07:01:18.174Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23910,
      ShippingOrderId: 21605,
      ShippingMethodId: 1,
    },
    {
      price: 867,
      vat: 52,
      discount: 0,
      certDiscount: null,
      shippingTax: 0,
      total: 867,
      shippingPrice: 0,
      saFloorNo: null,
      saFlatNo: null,
      id: 20689,
      guid: "f8667004-0989-47a3-b9d5-1f12b5fd8f42",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-14T11:15:39.485Z",
      updatedAt: "2021-09-14T11:15:43.107Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23825,
      ShippingOrderId: 21580,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20691,
      guid: "18fa06a2-492f-4296-863f-1591316562dc",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-15T11:44:07.463Z",
      updatedAt: "2021-09-15T11:44:10.918Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23838,
      ShippingOrderId: 21584,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20694,
      guid: "b11620e5-84e1-44e4-bebb-f0d8be745e85",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-20T08:05:40.532Z",
      updatedAt: "2021-09-20T08:05:41.104Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23885,
      ShippingOrderId: null,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20708,
      guid: "fd216f13-f8e4-4b71-a518-7dd1f03e293f",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-10-25T07:02:08.836Z",
      updatedAt: "2021-10-25T07:02:11.851Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23911,
      ShippingOrderId: 21606,
      ShippingMethodId: 1,
    },
    {
      price: 578,
      vat: 35,
      discount: 0,
      certDiscount: null,
      shippingTax: 0,
      total: 578,
      shippingPrice: 0,
      saFloorNo: null,
      saFlatNo: null,
      id: 20695,
      guid: "4d9e2269-e34c-4440-af70-2771ce3b3797",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-20T08:06:07.213Z",
      updatedAt: "2021-09-20T08:06:10.660Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23886,
      ShippingOrderId: 21589,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20677,
      guid: "7d0d9144-c525-4ed0-89cc-da08c44448a2",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+4632425325",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem",
      buyerLastName: "Morpeh",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-08T11:18:29.132Z",
      updatedAt: "2021-09-08T11:18:29.576Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23810,
      ShippingOrderId: null,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20696,
      guid: "351f57c7-3688-4fd3-95f1-dd8fbf04d049",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+462222222222",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem1",
      buyerLastName: "Morpeh1",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-20T08:06:40.185Z",
      updatedAt: "2021-09-20T08:06:43.150Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23887,
      ShippingOrderId: 21590,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20679,
      guid: "5f7ffe75-31b2-4054-8c2f-37805e0474e0",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+4632425325",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem",
      buyerLastName: "Morpeh",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-08T11:20:20.230Z",
      updatedAt: "2021-09-08T11:20:20.791Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23812,
      ShippingOrderId: null,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20680,
      guid: "b734cf06-0698-4ff7-9bee-87bb3f3a2037",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+4632425325",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem",
      buyerLastName: "Morpeh",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-08T11:20:25.042Z",
      updatedAt: "2021-09-08T11:20:25.492Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23813,
      ShippingOrderId: null,
      ShippingMethodId: 1,
    },
    {
      price: 289,
      vat: 17,
      discount: 0,
      certDiscount: null,
      shippingTax: 3,
      total: 338,
      shippingPrice: 49,
      saFloorNo: null,
      saFlatNo: null,
      id: 20681,
      guid: "e7734505-8cfb-497b-b146-a396f9f48049",
      notes: null,
      delivery: null,
      message: null,
      reason: null,
      status: "waiting",
      seenUser: null,
      seenSeller: null,
      expire: null,
      reactedAt: null,
      approved: null,
      delivered: null,
      canceled: null,
      declined: null,
      DiscountId: null,
      buyerPhone: "+4632425325",
      buyerEmail: "atest1one1@gmail.com",
      buyerFirstName: "Artem",
      buyerLastName: "Morpeh",
      buyerFullName: "Anton Morpeh",
      buyerBirthday: "1998-04-03T00:00:00.000Z",
      buyerStreetAddress: "OSLOGATAN",
      buyerStreetNumeric: "2",
      buyerEntrance: null,
      buyerCity: "Kista",
      buyerState: null,
      buyerCountry: "Sweden",
      buyerZip: "16432",
      buyerCoordinates: null,
      shippingMethod: "postnord",
      saStreetAddress: "OSLOGATAN",
      saStreetNumeric: "2",
      saCity: "Kista",
      saState: null,
      saCountry: "Sweden",
      saEntrance: null,
      saZip: "16432",
      saFloorType: null,
      saCoordinates: null,
      orderReference: null,
      createdAt: "2021-09-08T11:20:32.912Z",
      updatedAt: "2021-09-08T11:20:33.331Z",
      BuyerId: 49459,
      MerchantId: 34,
      ShippingAddressId: 36829,
      TransactionId: 23814,
      ShippingOrderId: null,
      ShippingMethodId: 1,
    },
  ],
};

const db = {};

function onDemandSaleStatus(book, db) {
	const period = new Date().getMonth() - 2
	const saleStatus = { low: 'low', medium: 'medium', high: 'high' }
	const bookSales = book.Sales

	if (!bookSales || bookSales.length === 0) {
		return saleStatus.low
	}

	const filter = (content, status) => _.filter(
		content,
		el => el.status === status && new Date(el.updatedAt).getMonth() >= period
	)

	const countByStatus = (status, orders = false) => {
		if (orders) {
			return orders && Array.isArray(orders) && orders.length > 0
				? filter(orders, status).length
				: 0
		}
		return bookSales && Array.isArray(bookSales) && bookSales.length > 0 ? filter(bookSales, status).length : 0
	}

	const available = countByStatus('available')
	const sold = countByStatus('sold')

	const orders = (function getOrders () {
		// eslint-disable-next-line max-len
		// return db.Product.findAll({ where: { BookId: book.id },	include: [db.Order]	}).then(products => _.map(products, p => p.Order))()
    return bookSale.orders
	}())

	const waiting = countByStatus('waiting', orders)
	const delivered = countByStatus('delivered', orders)

	const getAverage = (status1, status2) => {
		if (status1 === 0 && status2 === 0) {
			return 0
		}

		if (status1 === 0 && status2 > 0) return 100
		if (status2 === 0) return 0
		return Math.floor((status2 / status1) * 100)
	}

	const usedBookAverage = getAverage(available, sold)
	const newBookAverage = getAverage(waiting, delivered)

	if (usedBookAverage === 0 && newBookAverage === 0) {
		return saleStatus.low
	}

	const average = Math.floor((usedBookAverage + newBookAverage) / 2)

	if (average >= 0 && average < 34) return saleStatus.low
	if (average > 33 && average < 67) return saleStatus.medium
	return saleStatus.high
}

const saleOnDemandStatus = onDemandSaleStatus(bookSale, db);

console.log(typeof saleOnDemandStatus, saleOnDemandStatus);



// function oldOnDemandStatus(params)  {
// 	let onDemandSaleBookStatus
// 	const period = new Date().getMonth() - 2
// 	const saleStatus = { low: 'low', medium: 'medium', high: 'high' }

// 	if (!bookSales || bookSales.length === 0) {
// 		return saleStatus.low
// 	}

// 	const countByStatus = (status) => {
// 		if (bookSales && Array.isArray(bookSales) && bookSales.length > 0) {
// 			// eslint-disable-next-line max-len
// 			return _.filter(bookSales, sale => sale.status === status && new Date(sale.updatedAt).getMonth() >= period).length
// 		}
// 		return 0
// 	}

// 	const available = countByStatus('available')
// 	const sold = countByStatus('sold')

// 	if (available === 0 && sold === 0) {
// 		return saleStatus.low
// 	}

// 	if (available === 0 && sold > 0) onDemandSaleBookStatus = saleStatus.high
// 	else if (sold === 0) onDemandSaleBookStatus = saleStatus.low
// 	else if (available > 0 && sold > 0) {
// 		const ratio = Math.floor(sold / available * 100)
// 		if (ratio >= 0 && ratio < 34) onDemandSaleBookStatus = saleStatus.low
// 		else if (ratio > 33 && ratio < 67) onDemandSaleBookStatus = saleStatus.medium
// 		else if (ratio > 66) onDemandSaleBookStatus = saleStatus.high
// 	}

// 	return onDemandSaleBookStatus
// }

// async function createImageThumbnails(bookId, imageUrl, bucket) {
//   const fileExt = path.extname(imageUrl).slice(1).toLowerCase();
//   const extractedExtension = fileExt && fileExt.includes('?') ? fileExt.split('?')[0] : fileExt

//   if (!imageUrl || imageUrl === '' || !extensions.has(extractedExtension)) {
//     console.log(`createImageThumbnails : extensions = ${extensions}, imageUrl = ${imageUrl} `)
//     return Promise.resolve(null)
//   }



//   const el = _.first(_.map(supportingResource, (res) => { if (!res.ResourceVersion.ResourceLink.includes('3d')) return res } ))
